from .router_1 import router as router_1
from .router_2 import router as router_2
from .router_3 import router as router_3
from .router_4 import router as router_4
from .router_5 import router as router_5
from .router_6 import router as router_6
from .router_7 import router as router_7
from .router_8 import router as router_8
from .router_9 import router as router_9
from .router_10 import router as router_10
from .router_11 import router as router_11
from .router_12 import router as router_12
from .router_13 import router as router_13
from .router_14 import router as router_14
from .router_15 import router as router_15
from .router_16 import router as router_16
from .router_17 import router as router_17
from .router_18 import router as router_18
from .router_19 import router as router_19
from .router_20 import router as router_20
from .router_21 import router as router_21
from .router_22 import router as router_22
from .router_23 import router as router_23
from .router_24 import router as router_24
from .router_25 import router as router_25
from .router_26 import router as router_26
from .router_27 import router as router_27
from .router_28 import router as router_28
from .router_29 import router as router_29
from .router_30 import router as router_30
from .router_31 import router as router_31
from .router_32 import router as router_32
from .router_33 import router as router_33
from .router_34 import router as router_34
from .router_35 import router as router_35
from .router_36 import router as router_36
from .router_37 import router as router_37
from .router_38 import router as router_38
from .router_39 import router as router_39
from .router_40 import router as router_40
from .router_41 import router as router_41
from .router_42 import router as router_42
from .router_43 import router as router_43
from .router_44 import router as router_44
from .router_45 import router as router_45
from .router_46 import router as router_46
from .router_47 import router as router_47
from .router_48 import router as router_48
from .router_49 import router as router_49
from .router_50 import router as router_50
from .router_51 import router as router_51
from .router_52 import router as router_52
from .router_53 import router as router_53
from .router_54 import router as router_54
from .router_55 import router as router_55
from .router_56 import router as router_56
from .router_57 import router as router_57
from .router_58 import router as router_58
from .router_59 import router as router_59
from .router_60 import router as router_60
from .router_61 import router as router_61
from .router_62 import router as router_62
from .router_63 import router as router_63
from .router_64 import router as router_64
from .router_65 import router as router_65
from .router_66 import router as router_66
from .router_67 import router as router_67
from .router_68 import router as router_68
from .router_69 import router as router_69
from .router_70 import router as router_70
from .router_71 import router as router_71
from .router_72 import router as router_72
from .router_73 import router as router_73
from .router_74 import router as router_74
from .router_75 import router as router_75
from .router_76 import router as router_76
from .router_77 import router as router_77
from .router_78 import router as router_78
from .router_79 import router as router_79
from .router_80 import router as router_80
from .router_81 import router as router_81
from .router_82 import router as router_82
from .router_83 import router as router_83
from .router_84 import router as router_84
from .router_85 import router as router_85
from .router_86 import router as router_86
from .router_87 import router as router_87
from .router_88 import router as router_88
from .router_89 import router as router_89
from .router_90 import router as router_90
from .router_91 import router as router_91
from .router_92 import router as router_92
from .router_93 import router as router_93
from .router_94 import router as router_94
from .router_95 import router as router_95
from .router_96 import router as router_96
from .router_97 import router as router_97
from .router_98 import router as router_98
from .router_99 import router as router_99
from .router_100 import router as router_100
